name: lukelearnsthecloud-local
services:
  web:
    image: node:18-alpine
    ports:
      - '5173:5173'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    tty: true

volumes:
  node_modules:
    driver: local
