name: Build and Deploy Website to S3 & CloudFront

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  BUCKET_NAME: 'lukelearnsthe.cloud'
  AWS_REGION: 'us-east-1'

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::021891593951:role/github-actions-role
          role-session-name: test-github-actions-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy dist folder to S3
        run: |
          aws s3 sync dist/ s3://${{ env.BUCKET_NAME }}/ --delete
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2N6KLWY1L9MPP --paths '/*'
